name: install and test the project

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: istalling
        run: make install
