name: install and test the project

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: istalling
        run: make install
      - name: linting
        run: make lint
      - name: testing
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
