name: testing

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: building
        run: make install
      - name: eslint
        run: make lint
      - name: jest
        run: make test